### PR TITLE
Fix tests when no VERSION file exists

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@lucasbrunialti  Thanks for improving the tests. Our of curiosity, which workflow did you follow to produce the error fixed by this commit ?

**Comment by lucasbrunialti** [comment]
I followed the steps in here (https://github.com/j0057/github-release#testing):
> To execute the integration tests locally, and make sure your awesome contribution is working as expected, you will have to:
> - create a test repository with at least one commit (e.g yourname/github-release-test)
> - set environment variable INTEGRATION_TEST_REPO_NAME=yourname/github-release-test
> - execute python setup.py test

**Comment by lucasbrunialti** [comment]
Created this repo with a initial commit: https://github.com/lucasbrunialti/github-release-test

**Comment by jcfr** [comment]
Makes sense. Thanks for the rapid feedback.

**Pull request merged**
