### PR TITLE
Retry github get release operation with backoff

### PR DESCRIPTION
**Pull request by owais**

### CODE REVIEW

**Comment by owais** [comment]
@jcfr Please take a look. Thanks

**Comment by jcfr** [comment]
Thanks for the reminder 🙏. Will have a look this evening

**Comment by jcfr** [comment]
Thanks @owais and @dgerosa for the contributions :pray: 

The following additional changes have been added:
* To cover more cases, the retry has been associated with `get_releases` (instead of `get_release`).
* Instead of using the general exception `Exception`, the `backoff` decorator has been associated with the more specific `requests.exceptions.HTTPError` exception.

**Comment by jcfr** [comment]
To be more robust, we should probably introduce a new function called `_recursive_gh_get_with_retry` that would have be decorated with `backoff` and called from `get_releases/get_assets/get_refs` instead of `_recursive_gh_get`

@owais @dgerosa @miceno Would that be useful ?

**Comment by owais** [comment]
Thanks for the improvements. Honestly, anything that fixes my broken publish pipeline is acceptable but your improvement make a lot of sense. Thanks

**Comment by owais** [comment]
Thanks. Looking forward to the release.

**Comment by owais** [comment]
@jcfr Hi, any chance we can have a release soon? Thanks

**Pull request merged**
