### PR TITLE
support for parameterized github api url

### LINKED ISSUE #55: support for non public github URL
It would be a a good feature to be able to specify a private github URL rather than hardcoding the URL. The default should still be github.com

### PR DESCRIPTION
**Pull request by furlongm**
fixes #55

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :+1: 

Would it be possible to have a look at the following error:

```
./github_release.py:188: [E999] SyntaxError: invalid syntax
    global _github_api_url = github_api_url
                           ^
```  

I suggest to do this instead:

```python
global _github_api_url
_github_api_url = github_api_url
```

**Comment by furlongm** [comment]
Apologies, fixed that error. Travis checks seem to be failing now due to TOKEN not existing. Not sure if my change introduced that error?

**Comment by jcfr** [comment]
Thanks for updating the PR.

> Not sure if my change introduced that error

The failure are independent of your changes, the issue is that the `GITHUB_TOKEN` is not available for PR submitted from fork. I will fix the test so that they are skipped

**Comment by jcfr** [comment]
As soon as the CI is done, I will release a new version of the package on PyPi.

**Comment by jcfr** [comment]
See https://travis-ci.org/j0057/github-release/builds/518909935

**Pull request merged**
